version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10.15.0-jessie-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Test
          command: yarn test